In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [8]:
np.count_nonzero(a < 0)

4

In [9]:
np.count_nonzero(a > 0)

5

In [13]:
np.count_nonzero(a[(a > 0) & (a % 2 == 0)])

3

In [16]:
b = a + 3
np.count_nonzero(b > 0)

10

In [19]:
c = a ** 2
np.mean(c)

74.0

In [20]:
np.std(c)

144.0243035046516

In [82]:
zero = a - np.mean(a)
np.mean(zero)

0.0

In [80]:
e = (a - np.mean(a)/ np.std(a))
e

array([ 3.6278958,  9.6278958, 11.6278958, 22.6278958, -2.3721042,
       -1.3721042, -0.3721042, -0.3721042, -0.3721042, -6.3721042,
        2.6278958, -7.3721042])

In [ ]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = 0
for row in a:
    sum_of_a += sum(row)
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a[0]) if min(b[0]) <= min(a[1]) else min(a[1])  
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a[0]) if max(a[0]) >= max(a[1]) else max(a[1])
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = (sum(a[0]) + sum(a[1])) / (len(a[0]) + len(a[1]))
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for row in a:
    for number in row:
        product_of_a *= number

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = []
for row in a:
    for number in row:
        squares_of_a.append(number**2)

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for row in a:
    for number in row:
        if(number % 2 != 0):
            odds_in_a.append(number)

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for row in a:
    for number in row:
        if(number % 2 == 0):
            evens_in_a.append(number)

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [ ]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = np.array([
    [3, 4, 5],
    [6, 7, 8]])

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = b.sum()
# Exercise 2 - refactor the following to use numpy. 
min_of_b = b.min() 

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = b.max()

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = b.mean()

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = np.product(b)

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = np.square(b)

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = b[b % 2 == 1]


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = b[b % 2 == 0]

# Exercise 9 - print out the shape of the array b.
b.shape
# Exercise 10 - transpose the array b.
np.transpose(b)
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
np.reshape(b, (1, 6))
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
np.reshape(b, (6, 1))

In [28]:
## Setup 3
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
c.min()
c.max()
c.sum()
np.product(c)
# Exercise 2 - Determine the standard deviation of c.
np.std(c)
# Exercise 3 - Determine the variance of c.
np.var(c)
# Exercise 4 - Print out the shape of the array c
c.shape
# Exercise 5 - Transpose c and print out transposed result.
np.transpose(c)
c
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c)
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(np.transpose(c) * c)
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.product(np.transpose(c) * c)

array([23, -1,  3, -7])

In [86]:
## Setup 4
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)
# Exercise 4 - Find all the negative numbers in d
d[d < 0]
# Exercise 5 - Find all the positive numbers in d
d[ d > 0]
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)
# Exercise 7 - Determine how many unique numbers there are in d.
np.count_nonzero(np.unique(d)) + np.count_nonzero(np.unique(d == 0))
# Exercise 8 - Print out the shape of d.
d.shape
# Exercise 9 - Transpose and then print out the shape of d.
np.transpose(d)
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d, (9,2))

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [119]:
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [116]:
d.shape

(3, 6)

In [55]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np


131681894400

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])